spring.application.name=demo
# Gitea Konfiguracio
gitea.api.url=${GITEA_API_URL:http://gitea:3000/api/v1}
gitea.admin.username=${GITEA_ADMIN_USERNAME:legymernok_admin}
gitea.admin.password=${GITEA_ADMIN_PASSWORD}
gitea.admin.token=${GITEA_ADMIN_TOKEN}
#JWT Titkos kulcs
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
#Gitea
mission.verification.secret=${MISSION_VERIFICATION_SECRET}
gitea.template-repo-url="asd.com"
gitea.template.js.owner=legymernok_admin
gitea.template.js.repo=mission-js-template
gitea.template.python.owner=legymernok_admin
gitea.template.python.repo=mission-python-template
gitea.template.quiz.owner=legymernok_admin
gitea.template.quiz.repo=mission-quiz-template
gitea.template.circuit.owner=legymernok_admin
gitea.template.circuit.repo=mission-circuit-template
arduino.cli.path=arduino-cli
arduino.cli.compile.timeout-seconds=120